### PR TITLE
fix for godot 3.2.3

### PR DESCRIPTION
**Pull request by jice-nospam**
Hey, I had to make these changes to make it work with godot 3.2.3

### CODE REVIEW

**Comment by Zylann** [comment]
`$` is a shortcut for `get_node`. Why does this fix anything? What was the problem?

**Comment by jice-nospam** [comment]
I don't understand why, but after installing the add-on, there was an error on those files because the get_node function could not be found. That might be a godot bug but the $ version worked fine

**Comment by Zylann** [comment]
I could not get this to happen. I have this plugin installed in several projects and just tried installing it in a project that didnt have it, it worked fine.

However the following does still happen: https://github.com/godotengine/godot/issues/23937
And requires one or two restarts of the editor. That's an engine bug for which there is no fix because it relies on importing, and plugins can't trigger imports.

**Comment by jice-nospam** [comment]
yeah ok this change in the plugin code probably triggered some refresh in godot that fixed the compilation error. When I submitted the PR I thought the get_node function had been deprecated. Now it's up to you to accept or reject it. I personally find the $ syntax easier to read but it's not a big deal.
